# This workflow will setup and test the python code using miniconda

name: Setup and Test module

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: nrcat
          python-version: "3.10"
          channels: main, conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
      - run: |
            conda --version
            conda info
            conda list
            conda config --show-sources
            conda config --show
            conda info --envs
            python --version
            pip --version
            pwd
            ls -l
            pip install -r requirements.txt
            cd ./test
            pwd
            ls
            export LAL_DATA_PATH="${PWD}/test_data/lalsuite/lalsuite-extra/data/lalsimulation"
            echo $LAL_DATA_PATH
            mkdir -p $LAL_DATA_PATH
            cd $LAL_DATA_PATH
            wget https://git.ligo.org/lscsoft/lalsuite-extra/-/raw/master/data/lalsimulation/SEOBNRv4ROM_v2.0.hdf5
            cd ../../../../../
            pwd
            ls
            python -m unittest -v
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            ./test/logs/*


